### PR TITLE
2017 updates

### PR DESCRIPTION
**Pull request by fpigeon**
adds my notes to the install guide and additional resources

### CODE REVIEW

**Comment by aroman** [comment]
Thank you! Will review tonight :)

**Comment by fpigeon** [comment]
sounds good. Let me know if you have any questions.

**Comment by sdaitzman** [comment]
Wow, thank you @fpigeon!

**Comment by fpigeon** [comment]
@sdaitzman no problem. This is my first contribution to someone else's project so it was fun to figure out the process.

**Comment by aroman** [comment]
Awesome job, @fpigeon! Thanks so much for contributing. Glad we can merge this long-overdue update :)

**Comment by fpigeon** [comment]
I'm happy to help. This guide was very helpful for me to get dual-boot working so I am happy to contribute to it. Thanks for including my contributions with your project @aroman.

**Pull request merged**
