### PR TITLE
Moved rEFInd issue solving instructions to common issues section

### PR DESCRIPTION
**Pull request by peteruithoven**

### CODE REVIEW

**Comment by sdaitzman** [comment]
It should be clear that you do this from your Mac installation, but this looks good aside from that :smile:

**Comment by peteruithoven** [comment]
@sdaitzman I've tried to clarify that.

**Comment by sdaitzman** [comment]
Maybe “After installing rEFInd, reboot to OS X, open Terminal and do this:”

**Comment by aroman** [comment]
This is fixed in the current master :-)

**Pull request closed without merging**
